---

- hosts: servers
  gather_facts: False
  remote_user: root
  tasks:
    - name: check the host is reachable
      ping:
      delegate_to: localhost

    - import_tasks: ./task-pre-test.yml
    
    - name: clean data from neutron db tables
      mysql_db:
        name: "{{ neutrondb_database}}"
        login_user: neutron
        login_password: "{{ neutrondb_password }}"
        login_host: "{{ neutrondb_hostname }}"
        target: /tmp/delete-from-neutron-db.sql
        state: import

