---

- hosts: servers
  gather_facts: False
  remote_user: root
  tasks:
    - name: check the host is reachable
      ping:
      delegate_to: localhost

    - name: copy scripts to remote host
      copy: src={{ item }} dest=/tmp/ force=yes mode=0755
      with_fileglob:
        - ./*.sh
        - ./*.sql
    
    - name: clean data from neutron db tables
      mysql_db:
        name: "{{ neutrondb_database}}"
        login_user: neutron
        login_password: "{{ neutrondb_password }}"
        login_host: "{{ neutrondb_hostname }}"
        target: /tmp/delete-from-neutron-db.sql
        state: import

