---
- hosts: servers
  remote_user: root
  gather_facts: False
  tasks:
    - name: Set project and network range
      set_fact:
        test_range: "{{ range(0, projects, 1) | list }}"
      tags:
        - project
        - network
    
    - name: Create projects
      shell: |
        source {{ openrc }} && openstack project create --or-show proj_{{ item }} \
        && openstack role add --project proj_{{ item }} --user admin admin
      with_items: "{{ test_range }}"
      tags:
        - project
      
    - name: Reset resource quotas
      shell: |
        for n in loadbalancer healthmonitor l7policy listener member pool; do
          echo -n "$n .. " 
          neutron --os-project-name proj_{{ item }} quota-update --$n -1 > /dev/null 2>&1
        done
      with_items: "{{ test_range }}"
      tags:
        - project

    - name: Create networks
      shell: |
        source {{ openrc }}
        project_id=`openstack project show proj_{{ item }} --format value --column id`
        exists=`neutron net-list --format value --column name | grep "^net-{{ item }}$"`
        set -e
        if [ $? -eq 0 -a "$exists" != "net-{{ item }}" ]; then
          neutron net-create --tenant-id $project_id --provider:network_type vlan --provider:physical_network extnet net-{{ item }}
          neutron subnet-create --tenant-id $project_id --name subnet-{{ item }} net-{{ item }} 100.{{ item }}.0.0/16
        fi
      with_items: "{{ test_range }}"
      tags:
        network
