---

- hosts: servers
  remote_user: root
  gather_facts: false
  tasks:
    - import_tasks: ./task-set-testsuite.yml
      delegate_to: localhost
      tags:
        - loadbalancer
        - listener
        - pool
        - healthmonitor
        - member

    - import_tasks: ./task-pre-test.yml
      tags:
        - loadbalancer
        - listener
        - pool
        - healthmonitor
        - member

    - name: create loadbalancer
      shell: |
        source {{ openrc }}
        set -e
        exists=`/tmp/if-exists-resource.sh loadbalancers lb-{{ index_pj }} {{ neutrondb_password }}`
        if [ "$exists" = "false" ]; then
          neutron --os-project-id {{ project_id.stdout }} lbaas-loadbalancer-create \
            --name lb-{{ index_pj }} --tenant-id {{ project_id.stdout }} subnet-{{ index_pj }}
        fi
      tags: loadbalancer

    - name: create pools
      shell: |
        source {{ openrc }}
        set -e
        /tmp/wait-for-lb-done.sh lb-{{ index_pj }} {{ neutrondb_password }}
        exists=`/tmp/if-exists-resource.sh pools pl-{{ index_pj }}-{{ item }} {{ neutrondb_password }}`
        if [ "$exists" = "false" ]; then
          neutron --os-project-id {{ project_id.stdout }} lbaas-pool-create \
            --name pl-{{ index_pj }}-{{ item }} --tenant-id {{ project_id.stdout }} \
            --loadbalancer lb-{{ index_pj }} \
            --protocol HTTP --lb-algorithm ROUND_ROBIN
        fi
      with_items: "{{ range(0 , count_pl|int, 1) | list }}"
      tags: pool

    - name: create healthmonitors
      shell: |
        source {{ openrc }}
        set -e
        /tmp/wait-for-lb-done.sh lb-{{ index_pj }} {{ neutrondb_password }}
        exists=`/tmp/if-exists-resource.sh healthmonitors hm-{{ index_pj }}-{{ item }} {{ neutrondb_password }}`
        if [ "$exists" = "false" ]; then
          neutron --os-project-id {{ project_id.stdout }} lbaas-healthmonitor-create \
            --name hm-{{ index_pj }}-{{ item }}  --tenant-id {{ project_id.stdout }} \
            --pool pl-{{ index_pj }}-{{ item }} \
            --delay 15 --timeout 15 --max-retries 5 --type PING
        fi
      with_items: "{{ range(0 , count_hm|int, 1) | list }}"
      tags: healthmonitor

    - name: create listeners
      shell: |
        source {{ openrc }}
        set -e
        /tmp/wait-for-lb-done.sh lb-{{ index_pj }} {{ neutrondb_password }}
        exists=`/tmp/if-exists-resource.sh listeners ls-{{ index_pj }}-{{ item }} {{ neutrondb_password }}`
        if [ "$exists" = "false" ]; then
          neutron --os-project-id {{ project_id.stdout }} lbaas-listener-create \
            --name ls-{{ index_pj }}-{{ item }} --tenant-id {{ project_id.stdout }} \
            --loadbalancer lb-{{ index_pj }} --default-pool pl-{{ index_pj }}-{{ item % (count_pl|int) }} \
            --protocol HTTP --protocol-port {{ item }}
        fi
      with_items: "{{ range(0 , count_ls|int, 1) | list }}"
      tags: listener
    
    - name: create members
      shell: |
        source {{ openrc }}
        set -e
        /tmp/wait-for-lb-done.sh lb-{{ index_pj }} {{ neutrondb_password }}
        exists=`/tmp/if-exists-resource.sh members mb-{{ index_pj }}-{{ item }} {{ neutrondb_password }}`
        if [ "$exists" = "false" ]; then
          neutron --os-project-id {{ project_id.stdout }} lbaas-member-create \
            --name mb-{{ index_pj }}-{{ item }} --tenant-id {{ project_id.stdout }} \
            --protocol-port 80 --subnet subnet-{{ index_pj }} \
            --address {{ index_pj|int + 1 }}.1.{{ item % (count_pl|int) }}.{{ item % 253 + 1 }} \
            pl-{{ index_pj }}-{{ item % (count_pl|int) }}
        fi
      with_items: "{{ range(0 , count_mb|int, 1) | list }}"
      tags: member
