---
- hosts: servers
  remote_user: root
  gather_facts: False
  tasks:
    - debug: msg="run with {{ indexes }}"

    - name: run test
      shell: |
        ansible-playbook \
          -i /root/f5-oslbaasv2-tools/f5-oslbaasv2-batchops/scripts/ansible-playbook/env.ini \
          -e@/root/f5-oslbaasv2-tools/f5-oslbaasv2-batchops/scripts/ansible-playbook/vars.yml \
          /root/f5-oslbaasv2-tools/f5-oslbaasv2-batchops/scripts/ansible-playbook/create-resources.yml \
          -e index={{ item }}
      with_items: "{{ indexes }}"
    
